MST-76: Versimpelde vl-proza-message component.
milieuinfo/uig-webcomponents pull request #160
Opened 2022-09-28 14:30 UTC by HugaertsDries

2022-09-28 14:41 UTC, HugaertsDries commented on src/legacy/proza-message/src/lib/vl-proza-message.js
> +      window.open(`/proza/#domeinen/${this._domain}/codes/${this._code}`, '_blank');
Link open ter discussie.

2022-09-28 15:40 UTC, HugaertsDries commented on src/legacy/proza-message/src/lib/vl-proza-message.js
> +    if(await this.__updatenIsToegelaten()) {
Nieuw project. Mss dat het mijn configuratie niet heeft meegenomen. Bekijk het.

2022-09-29 05:43 UTC, pascalriquier commented on src/legacy/proza-message/src/lib/vl-proza-message.scss
> +    background-color: $vl-amber !important;
ik ben persoonlijk niet zo'n fan van die gele achtergrond maar dat is functioneel dus met Kenzo te bekijken.

2022-09-29 05:59 UTC, wautergu approved these changes

2022-09-29 06:03 UTC, pascalriquier requested changes
zie comments

2022-09-29 06:03 UTC, pascalriquier commented on src/legacy/proza-message/src/lib/vl-proza-rest-client.js
> +    return ProzaRestClient.__fetchJson(`proza/domein/${domain}`, {cache: 'no-cache'})
evt commentaar bij de no-store en de no-cache waarom dat nodig is en waarom dat dan geen probleem is

2022-09-29 06:03 UTC, pascalriquier commented on src/legacy/proza-message/test/unit/vl-proza-message.test.html
> +            await awaitUntil(() => proza._typographyElement.textContent === 'barfoo');
checken dat het daarna in de cache(s) gewijzigd is, dus dat als je daarna de message ophaalt dat je wel degelijk de nieuwe krijgt, niet alleen op het scherm in de typography, maar ook bij het ophalen van de message dus

2022-09-29 06:33 UTC, HugaertsDries commented on src/legacy/proza-message/src/lib/vl-proza-message.js
> +      return messageCache[code];
de functie "__getRawMessage" is async. Dus de consument van deze functie await de promise.

2022-09-29 08:06 UTC, pascalriquier approved these changes

2022-09-29 08:56 UTC, Pieter-Beckers approved these changes

2022-09-29 09:56 UTC, merged