Feature/UI g 1461 search results
milieuinfo/uig-webcomponents pull request #38
Opened 2021-11-16 14:51 UTC by meirege

2021-11-18 10:19 UTC, LucasSledsens requested changes

2021-11-18 10:19 UTC, LucasSledsens commented on src/components/search-results/components/search-result/index.js
> +import { nativeVlElement, define } from "../../../../utils/core/";
`/`

2021-11-18 10:19 UTC, LucasSledsens commented on src/components/search-results/components/search-result/search-result.stories.js
> +  title: "custom-elements/vl-search-results/vl-search-result",
Zeker dat het een custom element is? 😄

2021-11-18 10:37 UTC, meirege commented on src/components/search-results/components/search-result/index.js
> +import { nativeVlElement, define } from "../../../../utils/core/";
Fixed.

2021-11-18 10:37 UTC, meirege commented on src/components/search-results/components/search-result/search-result.stories.js
> +  title: "custom-elements/vl-search-results/vl-search-result",
Idd 😄 tis aangepast.

2021-11-19 09:18 UTC, LucasSledsens approved these changes

2021-11-19 09:22 UTC, merged