Feature/http error message
milieuinfo/uig-webcomponents pull request #77
Opened 2022-02-22 15:29 UTC by maikemeu

2022-02-28 13:01 UTC, LucasSledsens requested changes

2022-02-28 13:17 UTC, maikemeu commented on src/components/http-error-message/config/index.js
> +  controls: { hideNoControlsWarning: true },
Staat erbij voor alle niet-custom stories omdat die controls daar gedisabled zijn

2022-03-07 09:57 UTC, LucasSledsens requested changes

2022-03-07 09:57 UTC, LucasSledsens commented on src/components/http-error-message/components/test/e2e/http-error-message-preset.js
> +import { VlElement, By } from '../../../../../utils/test';
Een test folder in de components folder is wat raar vind ik, dan zou ik eerder deze losse file bij de e2e test folder van de http-error-message zetten. Ik dacht eerst dat het om een specifieke component van de components folder ging.

2022-03-07 09:57 UTC, LucasSledsens commented on src/components/http-error-message/components/vl-http-404-message/test/e2e/http-404-message.spec.js
> +  it('as a user I can read the content of the erorr message', async () => {
typo

2022-03-07 09:57 UTC, LucasSledsens commented on src/components/http-error-message/config/index.js
> +  const errorCodeText = errorCode ? `${errorCode} ` : '';
Je kan een default parameter op deze manier oplossen: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

2022-03-07 09:57 UTC, LucasSledsens commented on src/components/http-error-message/test/e2e/http-error-message.js
> +    return secondSlotElements[0];
Ik zou de array destructuren, is iets leesbaarder en een mooiere oplossing. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2022-03-07 12:12 UTC, LucasSledsens approved these changes

2022-03-07 12:13 UTC, merged